HUSTLE-UMC/HUSTLE_server

src/main/java/com/sporthustle/hustle/src/university/entity/University.java, src/main/java/com/sporthustle/hustle/src/user/entity/User.java
- close #20 
- 유저 엔티티를 위한 대학 엔티티 생성 (다른 기능에서도 사용 가능)
- User 엔티티 연관관계 추가 
- 관련 이슈를 입력해주세요.
=> [Feat/#20] university 엔티티 코드 작성

src/main/java/com/sporthustle/hustle/src/sportevent/entity/SportEvent.java, src/main/java/com/sporthustle/hustle/src/sportposition/entity/SportPosition.java, src/main/java/com/sporthustle/hustle/src/user/entity/User.java, src/main/resources/application.yml
- close #24 
- 스포츠 종목 및 포지션 엔티티 생성
- 스포츠 종목 엔티티 추가
- 스포츠 포지션 엔티티 추가
- 테이블 명을 카멜케이스를 적용할지 스네이크케이스로 적용할지 고민입니다.
- ex) sportposition vs sport_position
=> [Feat/#24] 스포츠 종목 및 스포츠 포지션 엔티티 생성

src/main/java/com/sporthustle/hustle/src/user/UserService.java, src/main/java/com/sporthustle/hustle/src/user/entity/User.java, src/main/java/com/sporthustle/hustle/src/user/model/JoinReq.java
- close #28 
- 유저 엔티티 컬럼별 이름 설정을 따로 안해도 되는 상황
- 유저 엔티티 이름 변경 시 dto 및 로직에도 영향이 있으므로 상황에 맞게 수정
- 유저 엔티티 설정 변경
- 유저 엔티티 필드명 수정
file changed 참고
- 관련 이슈를 입력해주세요.
=> [Fix/#28] 유저 엔티티 설정 수정 및 이름 수정

src/main/java/com/sporthustle/hustle/src/club/entity/Club.java, src/main/java/com/sporthustle/hustle/src/sportposition/entity/SportPosition.java
- feat/#27 
- 동아리 엔티티 생성
- 동아리 엔티티 생성
- close #27
=> [Feat/#27] 동아리 엔티티 생성

src/main/java/com/sporthustle/hustle/common/config/SwaggerConfig.java, src/main/java/com/sporthustle/hustle/common/config/security/SecurityUtils.java, src/main/java/com/sporthustle/hustle/common/exception/ErrorCode.java, src/main/java/com/sporthustle/hustle/src/TestController.java
- feat/#34
- 로그인 후 서비스 이용을 위함 
- 토큰에서 이메일 추출
스크린샷을 첨부해주세요.
- close #34
=> [Feat/#34] 토큰을 통한 이메일 추출

src/main/java/com/sporthustle/hustle/common/exception/ErrorCode.java, src/main/java/com/sporthustle/hustle/src/university/UniversityRepository.java, src/main/java/com/sporthustle/hustle/src/user/UserService.java, src/main/java/com/sporthustle/hustle/src/user/entity/User.java, src/main/java/com/sporthustle/hustle/src/user/model/JoinReq.java
- fix/#39
- 회원가입 시 대학 입력 누락으로 인한 수정 
- 회원가입 시 대학 입력 누락으로 인한 수정 
스크린샷을 첨부해주세요.
- close #39
=> [Fix/#39] 회원가입 시 대학 입력 누락 수정

src/main/java/com/sporthustle/hustle/src/user/UserController.java, src/main/java/com/sporthustle/hustle/src/user/UserService.java, src/main/java/com/sporthustle/hustle/src/user/entity/User.java, src/main/java/com/sporthustle/hustle/src/user/model/ModifyUserInfoReq.java, src/main/java/com/sporthustle/hustle/src/user/model/ModifyUserInfoRes.java
- feat/#26
- 개인정보 수정 api 구현 
- 개인정보 수정 api 구현 
스크린샷을 첨부해주세요.
- close #26
=> [Feat] 개인정보 수정 api 구현 

src/main/java/com/sporthustle/hustle/src/user/UserService.java, src/main/java/com/sporthustle/hustle/src/user/entity/User.java, src/main/java/com/sporthustle/hustle/src/user/model/ModifyUserInfoReq.java
- fix/#44
- 회원 정보 수정 api 에서 비밀번호 수정 삭제
- 회원 정보 수정 api 에서 비밀번호 수정 삭제
스크린샷을 첨부해주세요.
- close #44
=> [Fix/#44] 회원 정보 수정 api 에서 비밀번호 수정 삭제

src/main/java/com/sporthustle/hustle/src/user/UserController.java, src/main/java/com/sporthustle/hustle/src/user/UserService.java, src/main/java/com/sporthustle/hustle/src/user/model/GetUserInformationRes.java
- feat/#43
- 회원 정보 수정을 위한 회원 정보 조회
- 회원 정보 수정을 위한 회원 정보 조회
스크린샷을 첨부해주세요.
- close #43
=> [Feat/#43] 회원 정보 수정을 위한 회원 정보 조회

src/main/java/com/sporthustle/hustle/competition/CompetitionService.java
- `Feature/#7`
- 서비스 코드에 크리티컬한 불필요 코드가 있어 제거하려고 합니다.
- 서비스 코드에 `@RestController` 어노테이션 제거
스크린샷을 첨부해주세요.
- 관련 이슈를 입력해주세요.
=> [Refactor] `CompetitionService` 리팩터링

src/main/java/com/sporthustle/hustle/competition/CompetitionService.java
- `Feature/#7`
- 불필요한 코드 리팩터링 추가
- `CompetitionService` 코드에 스웨거 어노테이션 삭제
스크린샷을 첨부해주세요.
- 관련 이슈를 입력해주세요.
=> [Refactor] `CompetitionService` 코드에 스웨거 어노테이션 삭제

.github/release-drafter-config.yml, .github/workflows/release-drafter.yml
- `Feature/#55`
- 배포 시 자동으로 Release Note 내용을 채우기 위해 추가합니다.
- `release-drafter` 설정 파일 추가
- `release-drafter` Github actions 추가
스크린샷을 첨부해주세요.
- #55
=> [Feature] 릴리즈 노트 초안 작성해주는 Github actions 설정 / 스크립트 추가

.github/workflows/gradle-ci.yml, src/test/resources/application.yml
- `Feature/#13`
- 빌드 성공 / 실패 여부, 테스트 코드 통과 여부를 PR 단계에서 확인합니다.
- Gradle build 워크플로우 스크립트 파일 작성
스크린샷을 첨부해주세요.
- #13
=> [Feature] Gradle CI 스크립트를 추가

src/main/java/com/sporthustle/hustle/common/config/SwaggerConfig.java
- feat/#67
- 프론트엔드 로컬 서버 추가 요청
- 프론트엔드 로컬 서버 추가
스크린샷을 첨부해주세요.
- close #67
=> [Feat/#67] 스웨거 - 프론트엔드 로컬 서버 추가

src/main/java/com/sporthustle/hustle/common/config/WebConfig.java
- fix/#71
- localhost:3000 cors 허용
- localhost:3000 cors 허용
스크린샷을 첨부해주세요.
- close #71
=> [Fix/#71] CORS 해결을 위한 출처 허용

src/main/java/com/sporthustle/hustle/common/config/WebConfig.java
- fix/#73
- cors 해결 코드에 대한 보안 이슈 해결
- cors 해결 코드에 대한 보안 이슈 해결
스크린샷을 첨부해주세요.
- close #73
=> [Fix/#73] cors 해결 코드에 대한 보안 이슈 해결

src/main/java/com/sporthustle/hustle/common/config/BuildConfig.java
- fix/#75
- swagger buildproperties bean 에러 해결
- swagger buildproperties bean 에러 해결
스크린샷을 첨부해주세요.
- close #75
=> [Fix/#75] swagger buildproperties bean 에러 해결

src/main/java/com/sporthustle/hustle/common/config/security/SecurityConfig.java
- fix/#80
- 작업 배경을 알려주세요.
- 스웨거 403에러 해결
스크린샷을 첨부해주세요.
- close #80
=> [Fix/#80] 스웨거 403에러 해결

src/main/java/com/sporthustle/hustle/common/config/WebConfig.java, src/main/java/com/sporthustle/hustle/common/config/security/SecurityConfig.java, src/main/java/com/sporthustle/hustle/common/consts/Constants.java
- `Fix/#69`
- Swagger 에서 GET 요청 외에 CORS 차단되어 API 테스트 불가
- 스프링 시큐리티에 CORS 설정 빈 작성
- 프론트엔드 로컬 주소 & 서버 도메인 CORS 허용하도록 추가
- 모든 HTTP 메소드 허용하도록 추가
- 스프링 MVC 에서 Cors 설정한 걸 스프링 시큐리티로 위임
**GET 외에 메소드에서 일어나는 CORS 오류**
**수정 이후 정상 동작**
- #69
=> [HotFix] Swagger 에서 CORS 오류로 GET 외의 요청이 가지 않는 오류 해결

build.gradle, src/main/java/com/sporthustle/hustle/common/config/S3Config.java, src/main/java/com/sporthustle/hustle/common/config/security/SecurityConfig.java, src/main/java/com/sporthustle/hustle/infra/s3/S3Controller.java, src/main/java/com/sporthustle/hustle/infra/s3/S3Service.java, src/main/java/com/sporthustle/hustle/infra/s3/dto/S3UploadResponseDTO.java, src/main/resources/application.yml
- feat/#18
- 사진 파일 업로드를 위한 s3 업로드 로직 추가
- s3 파일 업로드 로직 추가
스크린샷을 첨부해주세요.
- close #18
=> [Feat/#18] s3 파일 업로드

src/main/java/com/sporthustle/hustle/oauth/OAuthService.java, src/main/resources/application.yml
- fix/#93
- 개인 카카오 로그인 정보를 공식 카카오 로그인으로 변경
- 카카오 로그인 secret 정보 수정
스크린샷을 첨부해주세요.
- close #93
=> [Fix/#93] 카카오 로그인 secret 정보 수정

src/main/resources/application.yml
- fix/#97
- 카카오 로그인 리다이렉트 url 변경
- 카카오 로그인 리다이렉트 url 변경
스크린샷을 첨부해주세요.
- close #97
=> [Fix/#97] 카카오 로그인 리다이렉트 url 변경

src/main/resources/application.yml
- fix/#100
- 카카오 소셜 로그인 리다이렉트 url 프론트의 변경
- 카카오 소셜 로그인 리다이렉트 url 수정
스크린샷을 첨부해주세요.
- close #100
=> [Fix/#100] 카카오 소셜 로그인 리다이렉트 url 수정

.github/CODEOWNERS, .github/workflows/deploy-prod.yml, .github/workflows/gradle-ci.yml, appspec.yml, scripts/start.sh, scripts/stop.sh, src/test/java/com/sporthustle/hustle/jasypt/JasyptTest.java, src/test/resources/application.yml
- `Refactor#92`
- 수동 배포의 불편함이 있어 자동 배포 스크립트를 작성합니다.
- 배포 워크 플로우 추가
스크린샷을 첨부해주세요.
- #92 
워크 플로우 로직에 이상이 있을 확률이 높아 차근차근 수정하면서 작업하겠습니다.
=> CI/CD 스크립트를 작성합니다.
